name: TOC Interface Updater
description: Updates Interface versions found in World of Warcraft TOC metadata files
branding:
  icon: tag
  color: yellow
inputs:
  flavor:
    description: Interface version to default to
    default: retail
  beta:
    description: Include beta versions?
  ptr:
    description: Include PTR versions?
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run the TOC updater script
      run: python3 ${GITHUB_ACTION_PATH}/toc_interface_updater/update.py -f ${{ inputs.flavor }} ${{ inputs.beta != '' && '-b' || '' }} ${{ inputs.ptr != '' && '-p' || '' }}
      shell: bash
